"""Loading the classifier-ontology profile, and the corroboration sets derived from it.

The profile under ``data/classifier_ontology/`` maps each of HeAR's eight event labels onto AudioSet
ontology nodes and carries the AudioSet node table those mappings are expanded against. It is
generated by ``scripts/build_classifier_ontology_map.py`` from three commit-pinned artifacts and is
never hand-edited.

A HeAR label is corroborated by its mapped AudioSet node **or any descendant of that node**, so the
sets here are subtree closures rather than the single names a hand-written map would list. Every
name a set contains is an AudioSet ``display_name``, which is what YAMNet and AST both report.

The airway kind is the same construction from the other end: it is the closure of the ontology roots
named in ``taxonomy.airway_ontology_roots``, and both the AudioSet evidence labels and the HeAR
evidence labels are read off that one closure.

The design, the pinned versions and what the mapping replaced are in
``specs/20260910-classifier-ontology-mapping/design.md``.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import TYPE_CHECKING, Any, Iterable, Mapping, Sequence

if TYPE_CHECKING:  # pragma: no cover - import cycle would be runtime-only
    from senselab.audio.workflows.triage.config import TriageConfig

PROFILE_VERSION = "1"
"""Schema version of the profile file. A reader refuses any other value."""

PROFILE_DIR = Path(__file__).parent / "data" / "classifier_ontology"
"""Where the bundled profiles live, one dated JSON per build."""

AIRWAY_ROOTS_PATH = "taxonomy.airway_ontology_roots"
"""The configuration path naming the ontology roots whose closure is the airway kind."""

PROFILE_PATH_KEY = "airway.corroboration_profile"
"""The configuration path naming which profile to read; null takes the packaged latest."""


def _bundled_profile_path() -> Path:
    """The newest bundled profile.

    Returns:
        The last dated profile in the bundled directory.

    Raises:
        FileNotFoundError: If the package ships no profile, which makes airway corroboration
            unavailable rather than silently empty.
    """
    bundled = sorted(PROFILE_DIR.glob("*.json"))
    if not bundled:
        raise FileNotFoundError(
            f"no classifier-ontology profile in {PROFILE_DIR}; "
            "run `uv run python scripts/build_classifier_ontology_map.py`"
        )
    return bundled[-1]


def _validate(profile: Mapping[str, Any], source: str) -> None:
    """Reject a profile whose mapping does not close over its own node table.

    Args:
        profile: The parsed profile.
        source: Where it was read from, for the message.

    Raises:
        ValueError: If the schema version is unknown, if a mapped or corroborating node id is
            absent from the profile's AudioSet node table, or if a label resolves to nothing.
    """
    version = str(profile.get("profile_version"))
    if version != PROFILE_VERSION:
        raise ValueError(f"{source}: profile_version {version!r}, expected {PROFILE_VERSION!r}")
    classes = profile.get("audioset", {}).get("classes") or {}
    mapping = profile.get("mapping") or {}
    if not mapping:
        raise ValueError(f"{source}: carries no mapping")
    for label, entry in mapping.items():
        referenced = list(entry.get("audioset_ids") or []) + list(entry.get("corroborating_ids") or [])
        unknown = [node_id for node_id in referenced if node_id not in classes]
        if unknown:
            raise ValueError(f"{source}: {label} references AudioSet ids absent from the ontology: {unknown}")
        if not entry.get("corroborating_ids"):
            raise ValueError(f"{source}: {label} resolves to no AudioSet node")


@lru_cache(maxsize=None)
def load_classifier_ontology(path: str | None = None) -> dict[str, Any]:
    """Load and validate a classifier-ontology profile.

    Args:
        path: Profile path, or ``None`` for the newest bundled one.

    Returns:
        The validated profile.

    Raises:
        FileNotFoundError: If ``path`` names a file that does not exist. A named-but-absent profile
            is an operator error, not a reason to fall back to the bundled one.
        ValueError: If the profile fails validation.
    """
    resolved = _bundled_profile_path() if path is None else Path(path)
    if not resolved.exists():
        raise FileNotFoundError(f"classifier-ontology profile not found: {resolved}")
    profile: dict[str, Any] = json.loads(resolved.read_text())
    _validate(profile, str(resolved))
    return profile


def hear_labels(path: str | None = None) -> tuple[str, ...]:
    """Every HeAR event label the profile maps, in the detector's graph order.

    Args:
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        The eight labels.
    """
    return tuple(str(label) for label in load_classifier_ontology(path)["hear_labels"])


def corroboration_sets(path: str | None = None) -> dict[str, frozenset[str]]:
    """Each HeAR label's AudioSet corroboration set: its mapped node and every descendant.

    Args:
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        ``{HeAR label: AudioSet display names}``, one entry per HeAR label, none of them empty.
    """
    mapping = load_classifier_ontology(path)["mapping"]
    return {label: frozenset(entry["corroborating_names"]) for label, entry in mapping.items()}


def hear_labels_in_group(group: str, path: str | None = None) -> tuple[str, ...]:
    """The HeAR labels the profile assigns to one crosswalk group, in graph order.

    Args:
        group: A group name the profile uses, e.g. ``"cough"`` or ``"breath"``.
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        The group's HeAR labels.
    """
    mapping = load_classifier_ontology(path)["mapping"]
    return tuple(label for label in hear_labels(path) if mapping[label]["group"] == group)


def audioset_labels_for_group(group: str, path: str | None = None) -> tuple[str, ...]:
    """The union of the corroboration sets of every HeAR label in one group, sorted.

    Args:
        group: A group name the profile uses, e.g. ``"cough"`` or ``"breath"``.
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        The AudioSet display names, sorted so the tuple is stable across builds.
    """
    sets = corroboration_sets(path)
    return tuple(sorted({name for label in hear_labels_in_group(group, path) for name in sets[label]}))


def unemittable_by_yamnet(path: str | None = None) -> dict[str, tuple[str, ...]]:
    """Per HeAR label, the AudioSet classes in its corroboration set that YAMNet cannot report.

    Args:
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        ``{HeAR label: AudioSet display names}``, entries with nothing unemittable omitted.
    """
    mapping = load_classifier_ontology(path)["mapping"]
    return {
        label: tuple(entry["not_emittable_by_yamnet"])
        for label, entry in mapping.items()
        if entry["not_emittable_by_yamnet"]
    }


def _emittable(entry: Mapping[str, Any]) -> bool:
    """Whether any classifier reading this ontology has an output for the node.

    Args:
        entry: One node of the profile's AudioSet class table.

    Returns:
        ``True`` when the class is in AudioSet's released 527 or in YAMNet's 521.
    """
    return bool(entry["in_audioset_527"]) or bool(entry["in_yamnet_521"])


def _root_ids(roots: Sequence[str], profile: Mapping[str, Any]) -> list[str]:
    """Resolve ontology display names onto the profile's node ids.

    Args:
        roots: AudioSet display names.
        profile: A loaded profile.

    Returns:
        The node ids, in the order the names were given.

    Raises:
        ValueError: If a name is not an AudioSet class in this profile.
    """
    classes: Mapping[str, Any] = profile["audioset"]["classes"]
    ids_by_name = {str(entry["name"]): node_id for node_id, entry in classes.items()}
    unknown = sorted({str(root) for root in roots} - set(ids_by_name))
    if unknown:
        raise ValueError(
            f"{unknown} are not AudioSet classes in the classifier-ontology profile; "
            "a root must be an ontology display name"
        )
    return [ids_by_name[str(root)] for root in roots]


def _reachable(root_ids: Iterable[str], classes: Mapping[str, Any]) -> set[str]:
    """Every node id reachable from the roots through ``child_ids``, the roots included.

    Args:
        root_ids: Where the walk starts.
        classes: The profile's AudioSet class table.

    Returns:
        The closure's node ids.
    """
    seen: set[str] = set()
    stack = list(root_ids)
    while stack:
        node_id = stack.pop()
        if node_id in seen or node_id not in classes:
            continue
        seen.add(node_id)
        stack.extend(classes[node_id]["child_ids"])
    return seen


def audioset_labels_under_roots(roots: Sequence[str], path: str | None = None) -> tuple[str, ...]:
    """The emittable AudioSet display names in the subtree closure of the named roots, sorted.

    A node in neither AudioSet's released 527 nor YAMNet's 521 is left out: no classifier has an
    output for it, so it can never match.

    Args:
        roots: AudioSet display names the closure starts from.
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        The display names, sorted so the tuple is stable across builds.

    Raises:
        ValueError: If a root is not an AudioSet class in the profile.
    """
    profile = load_classifier_ontology(path)
    classes: Mapping[str, Any] = profile["audioset"]["classes"]
    reached = _reachable(_root_ids(roots, profile), classes)
    return tuple(sorted(str(classes[node_id]["name"]) for node_id in reached if _emittable(classes[node_id])))


def hear_labels_under_roots(roots: Sequence[str], path: str | None = None) -> tuple[str, ...]:
    """The HeAR labels whose every mapped AudioSet node lies in the closure of the named roots.

    Args:
        roots: AudioSet display names the closure starts from.
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        The HeAR labels, in the detector's graph order.

    Raises:
        ValueError: If a root is not an AudioSet class in the profile.
    """
    profile = load_classifier_ontology(path)
    reached = _reachable(_root_ids(roots, profile), profile["audioset"]["classes"])
    mapping = profile["mapping"]
    return tuple(
        label
        for label in hear_labels(path)
        if mapping[label]["audioset_ids"] and set(mapping[label]["audioset_ids"]) <= reached
    )


def airway_audioset_labels(config: TriageConfig) -> tuple[str, ...]:
    """The AudioSet labels that are airway evidence, from the configured ontology roots.

    Args:
        config: The triage configuration.

    Returns:
        The emittable display names in the roots' closure, sorted.

    Raises:
        ValueError: If the roots are unset, or if one is not an AudioSet class in the profile.
    """
    return audioset_labels_under_roots(config.require(AIRWAY_ROOTS_PATH), config.get(PROFILE_PATH_KEY))


def airway_hear_labels(config: TriageConfig) -> tuple[str, ...]:
    """The HeAR labels that are airway evidence, from the same configured ontology roots.

    Args:
        config: The triage configuration.

    Returns:
        The HeAR labels whose mapped node falls inside the roots' closure, in graph order.

    Raises:
        ValueError: If the roots are unset, or if one is not an AudioSet class in the profile.
    """
    return hear_labels_under_roots(config.require(AIRWAY_ROOTS_PATH), config.get(PROFILE_PATH_KEY))
