"""Loading the classifier-ontology profile, and the corroboration sets derived from it.

The profile under ``data/classifier_ontology/`` maps each of HeAR's eight event labels onto AudioSet
ontology nodes and carries the AudioSet node table those mappings are expanded against. It is
generated by ``scripts/build_classifier_ontology_map.py`` from three commit-pinned artifacts and is
never hand-edited.

A HeAR label is corroborated by its mapped AudioSet node **or any descendant of that node**, so the
sets here are subtree closures rather than the single names a hand-written map would list. Every
name a set contains is an AudioSet ``display_name``, which is what YAMNet and AST both report.

The design, the pinned versions and what the mapping replaced are in
``specs/20260910-classifier-ontology-mapping/design.md``.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Mapping

PROFILE_VERSION = "1"
"""Schema version of the profile file. A reader refuses any other value."""

PROFILE_DIR = Path(__file__).parent / "data" / "classifier_ontology"
"""Where the bundled profiles live, one dated JSON per build."""


def _bundled_profile_path() -> Path:
    """The newest bundled profile.

    Returns:
        The last dated profile in the bundled directory.

    Raises:
        FileNotFoundError: If the package ships no profile, which makes airway corroboration
            unavailable rather than silently empty.
    """
    bundled = sorted(PROFILE_DIR.glob("*.json"))
    if not bundled:
        raise FileNotFoundError(
            f"no classifier-ontology profile in {PROFILE_DIR}; "
            "run `uv run python scripts/build_classifier_ontology_map.py`"
        )
    return bundled[-1]


def _validate(profile: Mapping[str, Any], source: str) -> None:
    """Reject a profile whose mapping does not close over its own node table.

    Args:
        profile: The parsed profile.
        source: Where it was read from, for the message.

    Raises:
        ValueError: If the schema version is unknown, if a mapped or corroborating node id is
            absent from the profile's AudioSet node table, or if a label resolves to nothing.
    """
    version = str(profile.get("profile_version"))
    if version != PROFILE_VERSION:
        raise ValueError(f"{source}: profile_version {version!r}, expected {PROFILE_VERSION!r}")
    classes = profile.get("audioset", {}).get("classes") or {}
    mapping = profile.get("mapping") or {}
    if not mapping:
        raise ValueError(f"{source}: carries no mapping")
    for label, entry in mapping.items():
        referenced = list(entry.get("audioset_ids") or []) + list(entry.get("corroborating_ids") or [])
        unknown = [node_id for node_id in referenced if node_id not in classes]
        if unknown:
            raise ValueError(f"{source}: {label} references AudioSet ids absent from the ontology: {unknown}")
        if not entry.get("corroborating_ids"):
            raise ValueError(f"{source}: {label} resolves to no AudioSet node")


@lru_cache(maxsize=None)
def load_classifier_ontology(path: str | None = None) -> dict[str, Any]:
    """Load and validate a classifier-ontology profile.

    Args:
        path: Profile path, or ``None`` for the newest bundled one.

    Returns:
        The validated profile.

    Raises:
        FileNotFoundError: If ``path`` names a file that does not exist. A named-but-absent profile
            is an operator error, not a reason to fall back to the bundled one.
        ValueError: If the profile fails validation.
    """
    resolved = _bundled_profile_path() if path is None else Path(path)
    if not resolved.exists():
        raise FileNotFoundError(f"classifier-ontology profile not found: {resolved}")
    profile: dict[str, Any] = json.loads(resolved.read_text())
    _validate(profile, str(resolved))
    return profile


def hear_labels(path: str | None = None) -> tuple[str, ...]:
    """Every HeAR event label the profile maps, in the detector's graph order.

    Args:
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        The eight labels.
    """
    return tuple(str(label) for label in load_classifier_ontology(path)["hear_labels"])


def corroboration_sets(path: str | None = None) -> dict[str, frozenset[str]]:
    """Each HeAR label's AudioSet corroboration set: its mapped node and every descendant.

    Args:
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        ``{HeAR label: AudioSet display names}``, one entry per HeAR label, none of them empty.
    """
    mapping = load_classifier_ontology(path)["mapping"]
    return {label: frozenset(entry["corroborating_names"]) for label, entry in mapping.items()}


def hear_labels_in_group(group: str, path: str | None = None) -> tuple[str, ...]:
    """The HeAR labels the profile assigns to one crosswalk group, in graph order.

    Args:
        group: A group name the profile uses, e.g. ``"cough"`` or ``"breath"``.
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        The group's HeAR labels.
    """
    mapping = load_classifier_ontology(path)["mapping"]
    return tuple(label for label in hear_labels(path) if mapping[label]["group"] == group)


def audioset_labels_for_group(group: str, path: str | None = None) -> tuple[str, ...]:
    """The union of the corroboration sets of every HeAR label in one group, sorted.

    Args:
        group: A group name the profile uses, e.g. ``"cough"`` or ``"breath"``.
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        The AudioSet display names, sorted so the tuple is stable across builds.
    """
    sets = corroboration_sets(path)
    return tuple(sorted({name for label in hear_labels_in_group(group, path) for name in sets[label]}))


def unemittable_by_yamnet(path: str | None = None) -> dict[str, tuple[str, ...]]:
    """Per HeAR label, the AudioSet classes in its corroboration set that YAMNet cannot report.

    Args:
        path: Profile path, or ``None`` for the bundled one.

    Returns:
        ``{HeAR label: AudioSet display names}``, entries with nothing unemittable omitted.
    """
    mapping = load_classifier_ontology(path)["mapping"]
    return {
        label: tuple(entry["not_emittable_by_yamnet"])
        for label, entry in mapping.items()
        if entry["not_emittable_by_yamnet"]
    }
