"""REPORT: both products on every file and every outcome, no elements written, no matched text."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import pytest
import soundfile as sf

from senselab.audio.data_structures import AudioHints
from senselab.audio.workflows.triage.config import TriageConfig, load_triage_config
from senselab.audio.workflows.triage.nodes.common import software_agent, write_verdict
from senselab.audio.workflows.triage.nodes.report import ReportRenderError, report
from senselab.audio.workflows.triage.nodes.verdict import verdict as fold_verdict
from senselab.audio.workflows.triage.vocabulary import Outcome
from senselab.utils.prov_store import ProvStore

_SHA = "0" * 39 + "1"
_DURATION_S = 6.0
_RATE = 16000
_UNLABELLED_LABEL = "unlabelled"


def _write(tmp_path: Path, body: str) -> Path:
    """A partial config override on disk."""
    path = tmp_path / "override.yaml"
    path.write_text(body)
    return path


def _override(tmp_path: Path, body: str) -> TriageConfig:
    """The packaged config with one partial override merged over it."""
    return load_triage_config(_write(tmp_path, body))


def _png(tmp_path: Path) -> TriageConfig:
    """The packaged config with the report format declared as an image."""
    path = tmp_path / "report.yaml"
    path.write_text("report:\n  format: png\n")
    return load_triage_config(path)


def _capture_panels(monkeypatch: pytest.MonkeyPatch) -> list[list[dict[str, Any]]]:
    """Record the panel specifications every render is handed, without changing what it draws."""
    from senselab.audio.workflows.triage.nodes import report as report_module

    captured: list[list[dict[str, Any]]] = []
    real = report_module.plot_aligned_panels

    def _spy(audio: Any, panels: list[dict[str, Any]], **kwargs: Any) -> Any:  # noqa: ANN401
        captured.append([dict(panel) for panel in panels])
        return real(audio, panels, **kwargs)

    monkeypatch.setattr(report_module, "plot_aligned_panels", _spy)
    return captured


def _stub_the_drawing(monkeypatch: pytest.MonkeyPatch) -> None:
    """Replace the aligned-panel render with a bare figure, to time the store-reading path alone."""
    from matplotlib import pyplot

    from senselab.audio.workflows.triage.nodes import report as report_module

    monkeypatch.setattr(report_module, "plot_aligned_panels", lambda audio, panels, **kw: pyplot.figure())


def _seed_report_store(  # noqa: C901 — one independent block per node, as the graph itself has
    store: ProvStore,
    tmp_path: Path,
    *,
    full: bool = False,
    admit_failed: bool = False,
    words: Sequence[str] = ("the", "quick", "brown", "fox"),
    marked_words: Sequence[tuple[str, str]] = (),
    airway_labelled: Sequence[tuple[float, float]] = ((1.0, 1.3),),
    airway_unlabelled: Sequence[tuple[float, float]] = ((2.0, 2.3),),
    absent: dict[str, str] | None = None,
    classifiers: Sequence[tuple[str, float, str]] | None = None,
    yamnet_labels: Sequence[str] | None = None,
    skip_voice: bool = False,
    foreign_span_label: str | None = None,
    scan: str = "complete",
) -> None:
    """Write what a completed graph would have left behind, so REPORT has a store to read.

    Args:
        store: The store to seed.
        tmp_path: Where the plain stream and the envelope sidecar are written.
        full: Whether to seed every node's output. False seeds ADMIT and nothing else.
        admit_failed: Whether ADMIT refused the file, which is the outcome REPORT must still speak to.
        words: The consensus words, rendered verbatim unless a mark covers them.
        marked_words: ``(text, category)`` words the PII scan marked, appended to ``words``.
        airway_labelled: Extents AIRWAY put a label of interest on.
        airway_unlabelled: Extents AIRWAY looked at and did not label.
        absent: What PREPROCESS records as uncomputed, ``{derivative: ExceptionClass}``.
        classifiers: ``(name, grid_s, label)`` per window classifier; ``()`` writes none at all,
            which is the state a null threshold leaves behind. None writes the three defaults.
        yamnet_labels: One extra label per YAMNet window, for a category list long enough to truncate.
        skip_voice: Whether VOICE writes an activity and no verdict — the store's own reading of a
            node that raised.
        foreign_span_label: A ``label`` assertion over an envelope span generated by a node other
            than AIRWAY, which must not reach the airway lane.
        scan: ``"complete"`` writes SPEECH's ``pii_scan`` with every detector attempted,
            ``"incomplete"`` writes one with a failed detector, and ``"absent"`` writes none —
            which is what routing declining SPEECH leaves behind.
    """
    config = load_triage_config()
    software = software_agent(store)
    activity = store.activity(
        node="ADMIT", step=None, parameters={"audio_file": str(tmp_path / ("refused.wav" if admit_failed else "r.wav"))}
    )
    store.was_associated_with(activity, software)

    def _entity(prov_type: str, extent: tuple[float, float] | None, attributes: dict[str, Any]) -> str:
        """One seeded entity, generated and attributed like the node that would have written it."""
        entity_id = store.entity(prov_type=prov_type, extent=extent, attributes=attributes)  # type: ignore[arg-type]
        store.was_generated_by(entity_id, activity)
        store.was_attributed_to(entity_id, software)
        return entity_id

    if admit_failed:
        write_verdict(
            store, activity, software, node="ADMIT", outcome=Outcome.FAIL, kind=None, why="decode failure", detail={}
        )
        fold_verdict(store, None, config, None, run_dir=tmp_path)
        return

    (tmp_path / "streams").mkdir(parents=True, exist_ok=True)
    (tmp_path / "derivatives").mkdir(parents=True, exist_ok=True)
    samples = np.linspace(-0.4, 0.4, int(_DURATION_S * _RATE), dtype=np.float32)
    sf.write(str(tmp_path / "streams" / "plain.wav"), samples, _RATE)
    for name in ("recording", "plain"):
        _entity(
            "stream",
            (0.0, _DURATION_S),
            {"name": name, "path": "streams/plain.wav", "sampling_rate": _RATE, "channels": 1},
        )

    write_verdict(store, activity, software, node="ADMIT", outcome=Outcome.PASS, kind=None, why="it decodes", detail={})
    if not full:
        fold_verdict(store, None, config, None, run_dir=tmp_path)
        return

    store.agent(agent_type="model", model_id="openai/whisper-large-v3", commit_sha=_SHA)
    store.agent(agent_type="model", model_id="https://tfhub.dev/google/yamnet/1", unresolved_reason="TF-Hub URL pin")

    envelope = np.linspace(-60.0, -10.0, int(_DURATION_S * _RATE), dtype=np.float64)
    np.savez(tmp_path / "derivatives" / "energy_envelope.npz", envelope_dbfs=envelope, floor_dbfs=envelope - 20.0)
    preprocess = store.activity(node="PREPROCESS", step="envelope", parameters={})
    store.was_associated_with(preprocess, software)
    _entity(
        "measurement",
        None,
        {
            "name": "energy_envelope",
            "signal": "preemphasised",
            "path": "derivatives/energy_envelope.npz",
            "sampling_rate": _RATE,
        },
    )
    envelope_spans = [*airway_labelled, *airway_unlabelled]
    span_ids = {
        tuple(extent): _entity(
            "span",
            (extent[0], extent[1]),
            {"peak_over_floor_db": 24.0 + index, "k_db": 18.0, "signal": "preemphasised", "merged_proposals": 1},
        )
        for index, extent in enumerate(envelope_spans)
    }
    _entity(
        "span",
        (3.0, 3.8),
        {
            "family": "phonation",
            "member": "sustained",
            "duration_s": 0.8,
            "production": "voiced",
            "voiced_fraction": 1.0,
            "offset_criterion": "f0_stability",
            "signal": "preemphasised",
            "hop_s": 0.01,
        },
    )
    declared = (
        (("yamnet", 0.96, "Speech"), ("ast", 2.0, "Cough"), ("hear", 2.0, "Breathe"))
        if classifiers is None
        else tuple(classifiers)
    )
    for classifier, grid, label in declared:
        start = 0.0
        index = 0
        while start < _DURATION_S:
            extra = [yamnet_labels[index % len(yamnet_labels)]] if classifier == "yamnet" and yamnet_labels else []
            _entity(
                "measurement",
                (start, min(start + grid, _DURATION_S)),
                {
                    "name": f"{classifier}_window",
                    "classifier": classifier,
                    "signal": "plain",
                    "labels": [label, *extra],
                    "scores": {name: 0.9 for name in (label, *extra)},
                },
            )
            start += grid
            index += 1
        _entity(
            "measurement",
            None,
            {
                "name": f"{classifier}_windows",
                "classifier": classifier,
                "signal": "plain",
                "labels": [label],
                "windows_by_label": {label: ["seeded"]},
                "n_windows": 1,
            },
        )
    write_verdict(
        store,
        preprocess,
        software,
        node="PREPROCESS",
        outcome=Outcome.PASS,
        kind=None,
        why="conditioning complete",
        detail={"absent": dict(absent or {}), "derivatives": {}},
    )

    fold = store.activity(node="TAXONOMY", step="fold", parameters={})
    store.was_associated_with(fold, software)
    for kind, state in (("speech", "present"), ("airway", "present"), ("voice", "present")):
        _entity("kind", None, {"kind": kind, "state": state, "lines": {}, "stream": "plain"})
    write_verdict(
        store,
        fold,
        software,
        node="TAXONOMY",
        outcome=Outcome.PASS,
        kind=None,
        why="every kind is present",
        detail={"kinds": {"speech": "present", "airway": "present", "voice": "present"}},
    )

    route = store.activity(node="routing", step=None, parameters={})
    store.was_associated_with(route, software)
    for branch, kind in (("AIRWAY", "airway"), ("SPEECH", "speech"), ("VOICE", "voice")):
        _entity(
            "branch_decision",
            None,
            {
                "branch": branch,
                "kind": kind,
                "will_run": True,
                "kind_state": "present",
                "raw_state": "present",
                "forced_by_hint": False,
                "hint_tags": [],
                "unmapped_tags": [],
                "bad_map_values": {},
                "why": "kind_present",
                "stream": "plain",
            },
        )
    write_verdict(
        store,
        route,
        software,
        node="routing",
        outcome=Outcome.PASS,
        kind=None,
        why="runs: AIRWAY, SPEECH, VOICE",
        detail={"runs": ["AIRWAY", "SPEECH", "VOICE"], "skipped": [], "forced": [], "empty_set": False},
    )

    classify = store.activity(node="AIRWAY", step="classify", parameters={})
    store.was_associated_with(classify, software)
    for extent in airway_labelled:
        label_id = store.entity(
            prov_type="assertion",
            extent=(extent[0], extent[1]),
            attributes={"verb": "label", "label": "Cough", "hear_window_ids": [], "merged_proposals": 1},
        )
        store.was_generated_by(label_id, classify)
        store.was_attributed_to(label_id, software)
        store.was_derived_from(label_id, span_ids[tuple(extent)])
    if foreign_span_label is not None and airway_unlabelled:
        elsewhere = store.activity(node="TAXONOMY", step="label", parameters={})
        store.was_associated_with(elsewhere, software)
        target = span_ids[tuple(airway_unlabelled[0])]
        foreign = store.entity(
            prov_type="assertion",
            extent=(airway_unlabelled[0][0], airway_unlabelled[0][1]),
            attributes={"verb": "label", "label": foreign_span_label},
        )
        store.was_generated_by(foreign, elsewhere)
        store.was_attributed_to(foreign, software)
        store.was_derived_from(foreign, target)
    write_verdict(
        store,
        classify,
        software,
        node="AIRWAY",
        outcome=Outcome.PASS,
        kind="airway",
        why="a span carries a label of interest",
        detail={"labelled_n": len(airway_labelled), "by_label": {"Cough": len(airway_labelled)}, "flags": []},
    )

    consensus = store.activity(node="PREPROCESS", step="consensus", parameters={})
    store.was_associated_with(consensus, software)
    every_word = [(text, None) for text in words] + [(text, category) for text, category in marked_words]
    word_ids: list[str] = []
    for index, (text, category) in enumerate(every_word):
        extent = (0.2 * index, 0.2 * index + 0.15)
        word_id = _entity("word", extent, {"text": text, "confidence": 0.9, "recognizers": [], "index": index})
        word_ids.append(word_id)
        if category is not None:
            mark_id = _entity("assertion", extent, {"verb": "label", "label": "pii", "category": category})
            store.was_derived_from(mark_id, word_id)
    _entity(
        "measurement",
        None,
        {
            "name": "consensus_transcript",
            "signal": "plain",
            "words": [{"text": text} for text, _ in every_word],
            "word_ids": word_ids,
            "event_ids": [],
            "text": " ".join(text for text, _ in every_word),
        },
    )

    speech = store.activity(node="SPEECH", step="corroborate", parameters={})
    store.was_associated_with(speech, software)
    _entity(
        "span",
        (0.0, 1.0),
        {"family": "speech", "words_n": len(every_word), "attributed_to": "SPEAKER_00", "nontarget": False},
    )
    for _, category in marked_words:
        _entity(
            "pii",
            (0.0, 1.0),
            {"category": category, "source": "gliner", "occurrence": 0, "occurrences_n": 1, "recognizers": []},
        )
    if scan != "absent":
        _entity(
            "measurement",
            None,
            {
                "name": "pii_scan",
                "signal": "consensus_transcript",
                "scanned_by": ["gliner", "presidio", "rules"],
                "failed": ["presidio"] if scan == "incomplete" else [],
                "missing": [],
            },
        )
    write_verdict(
        store,
        speech,
        software,
        node="SPEECH",
        outcome=Outcome.PASS,
        kind="speech",
        why="words, spans, speakers and quality are in the store",
        detail={
            "speaker_count": 1,
            "words_n": len(every_word),
            "pii": {"categories": sorted({category for _, category in marked_words}), "n": len(marked_words)},
            "flags": [],
        },
    )

    voice = store.activity(node="VOICE", step=None, parameters={})
    store.was_associated_with(voice, software)
    if skip_voice:
        plan_only = store.activity(node="REDACT", step="plan", parameters={})
        store.was_associated_with(plan_only, software)
        fold_verdict(store, None, config, None, run_dir=tmp_path)
        return
    _entity(
        "span",
        (3.0, 3.8),
        {
            "family": "phonation",
            "member": "sustained",
            "production": "voiced",
            "duration_s": 0.8,
            "onset_kind": "period",
            "offset_kind": "criterion",
            "offset_criterion": "f0_stability",
            "marks_n": 12,
        },
    )
    write_verdict(
        store,
        voice,
        software,
        node="VOICE",
        outcome=Outcome.PASS,
        kind="voice",
        why="phonation spans measured; nothing contested",
        detail={"spans_n": 1, "phonation_s": 0.8, "gate_interval": "unmeasured", "flags": []},
    )

    plan = store.activity(node="REDACT", step="plan", parameters={})
    store.was_associated_with(plan, software)
    for _, category in marked_words:
        _entity("span", (0.0, 1.0), {"name": "redaction", "category": category})
    write_verdict(
        store,
        plan,
        software,
        node="REDACT",
        outcome=Outcome.PASS if marked_words else Outcome.FLAG,
        kind=None,
        why="every finding redacted" if marked_words else "no finding to redact",
        detail={"redactions_n": len(marked_words), "by_category": {}, "artifacts_withheld": not marked_words},
    )
    fold_verdict(store, None, config, None, run_dir=tmp_path)


class TestBothProductsAlways:
    """One summary and one JSON per file, whatever the graph concluded."""

    def test_a_full_run_emits_both(self, store: ProvStore, tmp_path: Path) -> None:
        """The ordinary path."""
        _seed_report_store(store, tmp_path, full=True)
        artifacts = report(store, tmp_path / "summary", _png(tmp_path))
        assert artifacts["summary"].exists() and artifacts["summary"].suffix == ".png"
        assert artifacts["json"].exists()

    def test_an_admit_refusal_emits_both_and_says_nothing_was_measured(self, store: ProvStore, tmp_path: Path) -> None:
        """A file ADMIT refused gets a report that says that, not an exception (V24)."""
        _seed_report_store(store, tmp_path, admit_failed=True)
        artifacts = report(store, tmp_path / "summary", _png(tmp_path))
        payload = json.loads(artifacts["json"].read_text())
        assert payload["verdict"]["triage"] == "discard"
        assert payload["branches"] == {}
        assert artifacts["summary"].exists()

    def test_a_store_holding_nothing_at_all_still_emits_both(self, store: ProvStore, tmp_path: Path) -> None:
        """Not even ADMIT concluded, so there is no verdict to read; the products are owed anyway."""
        artifacts = report(store, tmp_path / "summary", _png(tmp_path))
        payload = json.loads(artifacts["json"].read_text())
        assert payload["verdict"]["triage"] is None
        assert artifacts["summary"].exists()

    def test_the_packaged_config_emits_a_report(self, store: ProvStore, config: TriageConfig, tmp_path: Path) -> None:
        """The one unconditional product must be reachable with no override at all (I4)."""
        _seed_report_store(store, tmp_path, full=True)
        artifacts = report(store, tmp_path / "summary", config)
        assert artifacts["summary"].suffix == ".png"
        assert artifacts["json"].exists()

    def test_an_unknown_format_refuses(self, store: ProvStore, tmp_path: Path) -> None:
        """A typo must not fall through to a silent default."""
        _seed_report_store(store, tmp_path, full=True)
        with pytest.raises(ValueError, match="report.format"):
            report(store, tmp_path / "summary", _override(tmp_path, "report:\n  format: jpeg\n"))

    def test_pdf_is_reachable_by_config(self, store: ProvStore, tmp_path: Path) -> None:
        """The two forms carry the same claims; the choice does not change the content."""
        _seed_report_store(store, tmp_path, full=True)
        pdf_config = load_triage_config(_write(tmp_path, "report:\n  format: pdf\n"))
        artifacts = report(store, tmp_path / "summary", pdf_config)
        assert artifacts["summary"].suffix == ".pdf"

    def test_the_two_forms_carry_the_same_json(self, store: ProvStore, tmp_path: Path) -> None:
        """``report.format`` is a presentation choice and changes no claim."""
        _seed_report_store(store, tmp_path, full=True)
        as_png = json.loads(report(store, tmp_path / "png", _png(tmp_path))["json"].read_text())
        pdf_config = load_triage_config(_write(tmp_path, "report:\n  format: pdf\n"))
        as_pdf = json.loads(report(store, tmp_path / "pdf", pdf_config)["json"].read_text())
        assert as_png["steps"] == as_pdf["steps"]
        assert as_png["verdict"] == as_pdf["verdict"]
        assert as_png["transcript"] == as_pdf["transcript"]


class TestItWritesNoElements:
    """A rendering is not evidence."""

    def test_the_store_is_unchanged(self, store: ProvStore, tmp_path: Path) -> None:
        """No entity, no activity, no agent, no relation."""
        _seed_report_store(store, tmp_path, full=True)
        before = store.fingerprint()
        report(store, tmp_path / "summary", _png(tmp_path))
        assert store.fingerprint() == before


class TestItRespectsThePiiMarking:
    """No matched text appears anywhere in either product."""

    def test_a_marked_word_is_rendered_redacted_in_the_json(self, store: ProvStore, tmp_path: Path) -> None:
        """The store holds PII by design; every artifact must respect the marking."""
        _seed_report_store(store, tmp_path, full=True, marked_words=[("alice", "PERSON")])
        artifacts = report(store, tmp_path / "summary", _png(tmp_path))
        text = artifacts["json"].read_text()
        assert "alice" not in text
        assert "[PERSON]" in text

    def test_an_unmarked_word_is_rendered_verbatim(self, store: ProvStore, tmp_path: Path) -> None:
        """The marking is what redacts, not a blanket refusal to render words."""
        _seed_report_store(store, tmp_path, full=True, words=["hello"], marked_words=[])
        artifacts = report(store, tmp_path / "summary", _png(tmp_path))
        assert "hello" in artifacts["json"].read_text()

    def test_the_marked_word_never_reaches_the_drawn_lanes(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """The summary is redacted by the same rule as the JSON, not only the JSON."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, marked_words=[("alice", "PERSON")])
        report(store, tmp_path / "summary", _png(tmp_path))
        drawn = json.dumps(panels[0], default=str)
        assert "alice" not in drawn
        assert "[PERSON]" in drawn


class TestTheProvenanceIsEmbedded:
    """A hash identifies a run; the mapping is what makes it readable without the repository."""

    def test_the_config_hash_and_the_mapping_both_appear(self, store: ProvStore, tmp_path: Path) -> None:
        """Both, always."""
        _seed_report_store(store, tmp_path, full=True)
        payload = json.loads(report(store, tmp_path / "summary", _png(tmp_path))["json"].read_text())
        assert payload["provenance"]["config_hash"]
        assert payload["provenance"]["config"]["name"] == "senselab-triage/default"

    def test_every_model_carries_its_resolved_commit_or_a_reason(self, store: ProvStore, tmp_path: Path) -> None:
        """An agent whose commit could not be resolved appears with its reason, never with a bare ref."""
        _seed_report_store(store, tmp_path, full=True)
        payload = json.loads(report(store, tmp_path / "summary", _png(tmp_path))["json"].read_text())
        assert payload["provenance"]["models"]
        for model in payload["provenance"]["models"]:
            assert model["revision"] is not None or model["unresolved_reason"] is not None
            assert model["revision"] != "main"

    def test_the_senselab_commit_is_a_sha_or_a_reason(self, store: ProvStore, tmp_path: Path) -> None:
        """The run's own commit obeys the rule its models do."""
        _seed_report_store(store, tmp_path, full=True)
        payload = json.loads(report(store, tmp_path / "summary", _png(tmp_path))["json"].read_text())
        provenance = payload["provenance"]
        assert provenance["commit"] is not None or provenance["commit_unresolved_reason"] is not None
        assert provenance["commit"] != "main"

    def test_every_step_names_the_elements_behind_it(self, store: ProvStore, tmp_path: Path) -> None:
        """This is what makes the JSON a view of the store rather than a second copy of it."""
        _seed_report_store(store, tmp_path, full=True)
        payload = json.loads(report(store, tmp_path / "summary", _png(tmp_path))["json"].read_text())
        assert payload["steps"]
        for entry in payload["steps"].values():
            assert isinstance(entry["element_ids"], list)
            assert entry["element_ids"]

    def test_the_named_elements_are_in_the_store(self, store: ProvStore, tmp_path: Path) -> None:
        """An id that joins back to nothing is not a join key."""
        _seed_report_store(store, tmp_path, full=True)
        payload = json.loads(report(store, tmp_path / "summary", _png(tmp_path))["json"].read_text())
        named = [element for entry in payload["steps"].values() for element in entry["element_ids"]]
        assert named
        for element in named:
            assert store.get_entity(element).id == element


class TestTheSummaryLayers:
    """One shared time axis, drawn from the store."""

    def test_the_shared_axis_carries_every_layer_the_store_holds(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Waveform, envelope with floor, spans, phonation spans, the three label lanes, the branches."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True)
        report(store, tmp_path / "summary", _png(tmp_path))
        kinds = [panel["type"] for panel in panels[0]]
        assert kinds.count("segments") >= 5
        assert "waveform" in kinds and "features" in kinds

    def test_the_spectrogram_and_the_blocks_are_both_drawn(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A reviewer judging the output needs the time-frequency picture and the judgment beside it."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True)
        report(store, tmp_path / "summary", _png(tmp_path))
        kinds = [panel["type"] for panel in panels[0]]
        assert "spectrogram" in kinds
        assert kinds[-1] == "text"

    def test_the_blocks_carry_the_decision_the_transcript_and_the_categories(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """The content a reviewer judges the run by, on the page rather than only in the JSON."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, words=["hello", "world"])
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "triage:" in blocks and "release:" in blocks
        assert "hello world" in blocks
        assert "Speech" in blocks
        assert "AIRWAY" in blocks

    def test_labelled_and_unlabelled_spans_are_distinguishable(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """branch-airway.md requires it on the shared axis."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, airway_labelled=[(1.0, 1.3)], airway_unlabelled=[(2.0, 2.3)])
        report(store, tmp_path / "summary", _png(tmp_path))
        labels = {
            segment["label"] for panel in panels[0] if panel.get("name") == "airway" for segment in panel["segments"]
        }
        assert "unlabelled" in labels and "Cough" in labels

    def test_a_layer_the_store_does_not_hold_is_simply_absent(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Nothing raises for want of a derivative; a report is owed on every outcome."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path)
        report(store, tmp_path / "summary", _png(tmp_path))
        kinds = [panel["type"] for panel in panels[0]]
        assert "waveform" in kinds
        assert "features" not in kinds


class TestItReadsTheStoreOnceRatherThanPerWord:
    """The index behind the PII rule and the airway labels is built once, not per element."""

    def test_the_assertion_index_is_built_once(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Two readers ask the same reverse question; one pass over the assertions answers both."""
        from senselab.audio.workflows.triage.nodes import report as report_module

        calls: list[int] = []
        real = report_module._assertions_by_source

        def _counted(store_: ProvStore) -> dict[str, list[Any]]:
            calls.append(1)
            return real(store_)

        monkeypatch.setattr(report_module, "_assertions_by_source", _counted)
        _seed_report_store(store, tmp_path, full=True, marked_words=[("alice", "PERSON")])
        report(store, tmp_path / "summary", _png(tmp_path))
        assert len(calls) == 1

    def test_a_long_transcript_renders_in_bounded_time(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """800 words and 800 markings; per-word rescanning made this quadratic and then some."""
        _stub_the_drawing(monkeypatch)
        _seed_report_store(
            store,
            tmp_path,
            full=True,
            words=[],
            marked_words=[(f"name{index}", "PERSON") for index in range(800)],
        )
        started = time.monotonic()
        artifacts = report(store, tmp_path / "summary", _png(tmp_path))
        elapsed = time.monotonic() - started
        assert json.loads(artifacts["json"].read_text())["transcript"]["words_n"] == 800
        assert elapsed < 15.0, f"reading the store took {elapsed:.1f}s; the per-word rescan is back"


class TestARenderFailureKeepsTheJson:
    """The JSON is complete before the picture is drawn, and must not go down with it."""

    def test_the_json_survives_and_the_error_names_the_cause(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A consumer reading many files loses nothing because one page could not be drawn."""
        from senselab.audio.workflows.triage.nodes import report as report_module

        def _raise(*args: Any, **kwargs: Any) -> Any:  # noqa: ANN401
            raise RuntimeError("the canvas is gone")

        monkeypatch.setattr(report_module, "_render", _raise)
        _seed_report_store(store, tmp_path, full=True)
        with pytest.raises(ReportRenderError) as caught:
            report(store, tmp_path / "summary", _png(tmp_path))
        artifacts = caught.value.artifacts
        assert sorted(artifacts) == ["json"]
        assert json.loads(artifacts["json"].read_text())["verdict"]["triage"]
        assert "the canvas is gone" in str(caught.value)


class TestTheAbsentLanesAreOnThePage:
    """A lane not drawn must never read as a measured absence."""

    def test_an_unfitted_derivative_is_named_apart_from_an_errored_one(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A null config key and a crash are different facts about the run."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(
            store,
            tmp_path,
            full=True,
            absent={"phonation_spans": "ValueError", "alignment": "AttributeError", "silence": "LookupError"},
        )
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "ABSENT" in blocks
        assert "unfitted (a config key it reads is null): phonation_spans [ValueError]" in blocks
        assert "unavailable (a derivative it reads is absent): silence [LookupError]" in blocks
        assert "errored: alignment [AttributeError]" in blocks

    def test_the_recorded_message_is_rendered_beside_the_reading(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """PREPROCESS records which key was null; a page that showed only the class would drop it."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(
            store,
            tmp_path,
            full=True,
            absent={"phonation_spans": "ValueError: phonation_spans.silence_floor_db is null"},
        )
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "unfitted (a config key it reads is null)" in blocks
        assert "phonation_spans [ValueError: phonation_spans.silence_floor_db is null]" in blocks

    def test_a_lane_absence_carries_the_message_too(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """The lane line is where a reader looks first, so the attribution must reach it."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(
            store,
            tmp_path,
            full=True,
            absent={"yamnet_windows": "ValueError: yamnet.window_s is null"},
            classifiers=(),
        )
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "lane not drawn — yamnet labels: PREPROCESS/yamnet_windows unfitted" in blocks
        assert "yamnet.window_s is null" in blocks


class TestTheHintReadingIsOnThePage:
    """``verdict.hints`` reached the JSON and not the page, so a reader saw the flag and not its cause."""

    def test_an_unclaimed_kind_reads_found_unclaimed(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """With nothing declared, every kind the graph found is found and unclaimed, and says so."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True)
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "airway: screened=present resolved=present agreement=agree hint=found_unclaimed" in blocks

    def test_a_declared_kind_no_branch_found_reads_claimed_not_found(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """The reason line names the mismatch; the kind line must agree with it rather than omit it."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True)
        software = software_agent(store)
        supersede = store.activity(node="routing", step="declare", parameters={})
        store.was_associated_with(supersede, software)
        decision = store.entity(
            prov_type="branch_decision",
            extent=None,
            attributes={
                "branch": "AIRWAY",
                "kind": "airway",
                "will_run": True,
                "kind_state": "present",
                "raw_state": "present",
                "forced_by_hint": False,
                "hint_tags": ["cough"],
                "unmapped_tags": [],
                "bad_map_values": {},
                "why": "kind_present",
                "stream": "plain",
            },
        )
        store.was_generated_by(decision, supersede)
        refuted = store.activity(node="AIRWAY", step="reclassify", parameters={})
        store.was_associated_with(refuted, software)
        write_verdict(
            store,
            refuted,
            software,
            node="AIRWAY",
            outcome=Outcome.FAIL,
            kind="airway",
            why="spans exist but none carries a label of interest",
            detail={},
        )
        fold_verdict(store, None, load_triage_config(), AudioHints(may_contain=["cough"]), run_dir=tmp_path)

        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "airway: screened=present resolved=absent agreement=mismatch hint=claimed_not_found" in blocks

    def test_a_lane_the_page_did_not_draw_is_named_with_its_reason(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Under the packaged config the label lanes are missing; the page must say why."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, absent={"yamnet_windows": "ValueError"}, classifiers=())
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "lane not drawn — yamnet labels: PREPROCESS/yamnet_windows unfitted" in blocks

    def test_a_page_that_drew_every_lane_says_so(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Silence about absences is indistinguishable from having none."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, marked_words=[("alice", "PERSON")])
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "every declared lane was drawn" in blocks
        assert "PREPROCESS reports no absent derivative" in blocks


class TestThePageCarriesItsOwnProvenanceAndRunState:
    """A reviewer judging one page must not have to open the JSON to know where it came from."""

    def test_the_provenance_line_names_the_config_the_commit_and_the_models(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """The full model list stays in the JSON; the identity belongs on the page."""
        panels = _capture_panels(monkeypatch)
        config = _png(tmp_path)
        _seed_report_store(store, tmp_path, full=True)
        report(store, tmp_path / "summary", config)
        blocks = "\n".join(panels[0][-1]["lines"])
        assert f"config {config.config_hash}" in blocks
        assert "senselab " in blocks
        assert "models: 1 at a resolved commit, 1 with a reason" in blocks

    def test_the_ran_line_tells_an_errored_node_from_a_silent_one(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """The distinction the whole graph is built to preserve must reach the page."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, skip_voice=True)
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "ran: ADMIT:completed" in blocks
        assert "VOICE:errored" in blocks

    def test_the_branch_block_carries_its_measurements(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A branch conclusion without its numbers cannot be judged, only believed."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, marked_words=[("alice", "PERSON")])
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "speaker_count=1" in blocks
        assert "phonation_s=0.8" in blocks and "0.79999" not in blocks
        assert "words_n=5" in blocks
        assert "labelled_n=1" in blocks
        assert "redactions_n=1" in blocks

    def test_a_truncated_category_list_says_how_many_it_left_out(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Six of six and six of forty must not render identically."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, yamnet_labels=[f"L{index}" for index in range(9)])
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "yamnet (top 6 of " in blocks
        assert "top 6 of 6" not in blocks
        assert "ast:" in blocks


class TestTheRefusalPage:
    """The file ADMIT refused is the one that most needs a legible page."""

    def test_it_names_the_file_and_shows_unknowns_as_a_dash(self, store: ProvStore, tmp_path: Path) -> None:
        """A refusal page that cannot name the file, or that prints "None", is of no use."""
        _seed_report_store(store, tmp_path, admit_failed=True)
        artifacts = report(store, tmp_path / "summary", _png(tmp_path))
        payload = json.loads(artifacts["json"].read_text())
        assert payload["file"]["path"] is not None and payload["file"]["path"].endswith("refused.wav")
        assert payload["file"]["duration_s"] is None

    def test_the_page_itself_carries_the_name_the_dash_and_the_reason(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Everything the reviewer needs, with no Python repr leaking through."""
        drawn: list[list[str]] = []
        from senselab.audio.workflows.triage.nodes import report as report_module

        real = report_module._blocks

        def _spy(store_: ProvStore, marks: dict[str, Any], lanes: set[str], provenance: dict[str, Any]) -> list[str]:
            lines = real(store_, marks, lanes, provenance)
            drawn.append(lines)
            return lines

        monkeypatch.setattr(report_module, "_blocks", _spy)
        _seed_report_store(store, tmp_path, admit_failed=True)
        report(store, tmp_path / "summary", _png(tmp_path))
        blocks = "\n".join(drawn[0])
        assert "refused.wav" in blocks
        assert "duration: — s" in blocks
        assert "decode failure" in blocks
        assert ": None" not in blocks


class TestOnlyAirwayLabelsTheAirwayLane:
    """A label assertion is read as AIRWAY's only when AIRWAY generated it."""

    def test_a_label_from_another_node_does_not_reach_the_lane(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """The lane answers "what did AIRWAY conclude", not "what has anyone said over this span"."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, foreign_span_label="Applause")
        report(store, tmp_path / "summary", _png(tmp_path))
        labels = {
            segment["label"] for panel in panels[0] if panel.get("name") == "airway" for segment in panel["segments"]
        }
        assert "Applause" not in labels
        assert "Cough" in labels and _UNLABELLED_LABEL in labels


class TestElementIdsNameLiveEvidenceOnly:
    """A join key to a withdrawn element credits a claim to evidence that no longer stands."""

    def test_an_invalidated_entity_is_not_cited(self, store: ProvStore, tmp_path: Path) -> None:
        """The store's shared read rule applies to the report's citations too."""
        _seed_report_store(store, tmp_path, full=True)
        withdrawn = [entity for entity in store.entities("span") if entity.attributes.get("family") == "speech"][0]
        store.was_invalidated_by(withdrawn.id, store.activities("SPEECH")[0].id)
        payload = json.loads(report(store, tmp_path / "summary", _png(tmp_path))["json"].read_text())
        cited = [element for entry in payload["steps"].values() for element in entry["element_ids"]]
        assert withdrawn.id not in cited


class TestAnUnscannedTranscriptIsNotACleanOne:
    """The marking is what redacts, so no marking is only reassuring if something looked."""

    def test_a_transcript_nobody_scanned_is_withheld(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Routing declining SPEECH must not turn every word into a word cleared for rendering."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, words=["hello", "world"], scan="absent")
        artifacts = report(store, tmp_path / "summary", _png(tmp_path))
        text = artifacts["json"].read_text()
        assert "hello" not in text
        assert "[unscanned]" in text
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "TRANSCRIPT (WITHHELD" in blocks
        assert "no pii scan is in the store" in blocks

    def test_an_incomplete_scan_is_withheld_and_names_the_detector(
        self, store: ProvStore, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A scan that lost a detector is REDACT's own N15 case, and the page reads it the same way."""
        panels = _capture_panels(monkeypatch)
        _seed_report_store(store, tmp_path, full=True, words=["hello"], scan="incomplete")
        assert "hello" not in report(store, tmp_path / "summary", _png(tmp_path))["json"].read_text()
        blocks = "\n".join(panels[0][-1]["lines"])
        assert "detectors failed: presidio" in blocks

    def test_a_complete_scan_renders_the_words_it_cleared(self, store: ProvStore, tmp_path: Path) -> None:
        """Withholding everything unconditionally would make the marking pointless."""
        _seed_report_store(store, tmp_path, full=True, words=["hello"], marked_words=[("alice", "PERSON")])
        text = report(store, tmp_path / "summary", _png(tmp_path))["json"].read_text()
        assert "hello" in text
        assert "[PERSON]" in text
        assert "alice" not in text
        assert "[unscanned]" not in text
