"""Assemble the single-file viewer by inlining every part into the shell.

The shell carries ``/*@INLINE:<path>@*/`` markers; each is replaced by that file's text. The
output is a pure function of the parts, with no timestamp and no host in it, so a test can
rebuild and compare bytes.
"""

from __future__ import annotations

import re
from pathlib import Path

SOURCE_DIR = Path(__file__).parent
SHELL = SOURCE_DIR / "shell.html"
BUILT_PAGE = SOURCE_DIR / "recording_vectors_viewer.html"

INLINE_PATTERN = re.compile(r"/\*@INLINE:(?P<path>[^@]+)@\*/")

PARTS = (
    "styles.css",
    "vendor/hyparquet-1.31.1-fzstd-0.1.1.bundle.js",
    "decode.js",
    "axes.js",
    "corpus.js",
    "recording.js",
    "app.js",
)

BANNER = """<!--
  Built from src/senselab/audio/workflows/triage/viewer/ by its build.py. Do not edit this file;
  edit the parts and rebuild with `uv run python scripts/triage_vectors_viewer.py`.

  Reads recording_vectors.parquet, schema_version 1, whose byte layout is specified in
  specs/20260922-compact-recording-vectors/schema.md.

  This page renders transcript text and detected PII extents. It is opened from file:// by the
  owner of the data and is never hosted.

  Vendored: hyparquet 1.31.1 (MIT) and fzstd 0.1.1 (MIT), bundled with esbuild as an IIFE.
-->"""


def _inline(match: re.Match[str]) -> str:
    """Replace one marker with the text of the file it names.

    Args:
        match: The ``/*@INLINE:path@*/`` match.

    Returns:
        The file's text, with no trailing newline of its own.

    Raises:
        FileNotFoundError: When the named part is missing.
    """
    part = SOURCE_DIR / match.group("path")
    if not part.is_file():
        raise FileNotFoundError(f"{part} is named by the shell but does not exist")
    return part.read_text(encoding="utf-8").rstrip("\n")


def build(shell: Path | None = None) -> str:
    """The whole page, as one string.

    Args:
        shell: The template, or None for the packaged ``shell.html``.

    Returns:
        The assembled HTML.

    Raises:
        ValueError: When the shell names a part that is not in :data:`PARTS`.
    """
    text = (shell or SHELL).read_text(encoding="utf-8")
    named = set(INLINE_PATTERN.findall(text))
    unexpected = named - set(PARTS)
    if unexpected:
        raise ValueError(f"the shell inlines {sorted(unexpected)}, which PARTS does not list")
    missing = set(PARTS) - named
    if missing:
        raise ValueError(f"PARTS lists {sorted(missing)}, which the shell does not inline")
    return INLINE_PATTERN.sub(_inline, text).replace("<!--@BUILD@-->", BANNER)


def write(destination: Path | None = None) -> Path:
    """Build the page and write it.

    Args:
        destination: Where to write, or None for the committed :data:`BUILT_PAGE`.

    Returns:
        The path written.
    """
    target = destination or BUILT_PAGE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(build(), encoding="utf-8")
    return target
