"""Behavioural tests for the differential over a replayed store.

Nothing here is faked. Each fixture is a real :class:`ProvStore` written, read back under the
replay's own run id, retired with :func:`retire_decisions` and written again, which is the exact
sequence the replay driver performs. The properties asserted are the ones the differential rests
on: that the two passes are recoverable from the invalidation edges alone, that a decision which
did not move reads as identical, that a field the replay added is not a move, and that nothing the
store holds as text reaches a row.

``specs/20260922-replay-decisions-over-a-finished-corpus/differential.md`` is the design.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from senselab.audio.workflows.triage.extend import (
    REPLAY_MARKER_STEP,
    REPLAY_NODE,
    live_decisions,
    retire_decisions,
)
from senselab.audio.workflows.triage.nodes.common import software_agent, write_verdict
from senselab.audio.workflows.triage.replay_diff import (
    ADMIT_DID_NOT_ADMIT,
    AMBIGUOUS,
    NO_STORE,
    NOT_REPLAYABLE,
    NOT_REPLAYED,
    NOTHING_RETIRED,
    OK,
    PREPROCESS_DID_NOT_COMPLETE,
    aggregate,
    diff_run,
    diff_store,
    generation,
    read_rows,
    render_markdown,
    split_generations,
    write_report,
)
from senselab.audio.workflows.triage.vocabulary import (
    FileVerdict,
    NodeVerdict,
    Outcome,
    Release,
    RunState,
    Triage,
)
from senselab.utils.prov_store import ProvStore

SECRET = "Marguerite Okonkwo of 14 Ellery Street"
"""A string standing in for what a transcript and a PII finding carry. It must reach no row."""


def _fold(
    triage: Triage = Triage.PASS,
    *,
    reasons: list[NodeVerdict] | None = None,
    deviations: dict[str, list[str]] | None = None,
    ran: dict[str, RunState] | None = None,
    **kwargs: Any,  # noqa: ANN401 — whatever FileVerdict field a test varies
) -> FileVerdict:
    """One file-level decision, defaulting everything a test does not vary.

    Args:
        triage: The triage outcome.
        reasons: The contributing verdicts.
        deviations: Node to the deviation types it reported.
        ran: Node to its run state.
        kwargs: Any other :class:`FileVerdict` field.

    Returns:
        The fold.
    """
    return FileVerdict(
        triage=triage,
        release=Release.NOT_ASSESSED,
        declared_family="syllable",
        reasons=reasons or [],
        deviations=deviations or {},
        ran=ran or {"SPEECH": RunState.COMPLETED, "REDACT": RunState.SKIPPED},
        **kwargs,
    )


def _write_pass(
    store: ProvStore,
    fold: FileVerdict,
    *,
    extra: dict[str, Any] | None = None,
    drop: tuple[str, ...] = (),
    branch_deviations: tuple[str, ...] = (),
    deviation_assertions: tuple[str, ...] = (),
    pii_categories: tuple[str, ...] = (),
    scanned: bool = True,
) -> None:
    """Write one pass's decision into a store, as the graph's nodes would.

    Args:
        store: The store to write into.
        fold: The file-level decision.
        extra: Decision fields to add, standing for a field a later commit introduced.
        drop: Decision fields to remove, standing for a field the commit that ran did not have.
        branch_deviations: The deviation types SPEECH's own report carries.
        deviation_assertions: One ``deviate`` assertion per name, generated by SPEECH, each over
            its own extent so that two of a type are two entities and not one.
        pii_categories: One ``pii`` entity per name, generated by SPEECH.
        scanned: Whether SPEECH's scan ran, which its ``pii_scan`` measurement records.
    """
    agent = software_agent(store)
    speech = store.activity(node="SPEECH", step="pii", parameters={})
    store.was_associated_with(speech, agent)
    report_id = store.entity(
        prov_type="branch_report",
        extent=None,
        attributes={
            "node": "SPEECH",
            "kind": "speech",
            "conformance": True,
            "conformance_of": "task",
            "deviations": list(branch_deviations),
            "unmeasured": [],
            "in_family": True,
        },
    )
    store.was_generated_by(report_id, speech)
    for index, name in enumerate(deviation_assertions):
        assertion = store.entity(
            prov_type="assertion",
            extent=(float(index), float(index) + 1.0),
            attributes={"verb": "deviate", "deviation_type": name, "surface": SECRET},
        )
        store.was_generated_by(assertion, speech)
    for category in pii_categories:
        finding = store.entity(
            prov_type="pii",
            extent=None,
            attributes={"category": category, "source": "rules", "haystack": "consensus", "text": SECRET},
        )
        store.was_generated_by(finding, speech)
    scan = store.entity(
        prov_type="measurement",
        extent=None,
        attributes=(
            {"name": "pii_scan", "signal": "consensus", "scanned": False, "why": "nothing outside the stimulus"}
            if not scanned
            else {"name": "pii_scan", "signal": "consensus_transcript", "scanned_by": ["rules"], "failed": []}
        ),
    )
    store.was_generated_by(scan, speech)
    word = store.entity(prov_type="word", extent=(0.0, 1.0), attributes={"index": 0, "text": SECRET})
    preprocess = store.activity(node="PREPROCESS", step="consensus", parameters={})
    store.was_generated_by(word, preprocess)
    deciding = store.activity(node="VERDICT", step=None, parameters={})
    store.was_associated_with(deciding, agent)
    write_verdict(
        store,
        deciding,
        agent,
        node="VERDICT",
        outcome=fold.triage,
        kind=None,
        why="folded the fixture's nodes",
        detail={key: value for key, value in {**fold.record(), **(extra or {})}.items() if key not in drop},
    )


def _admit(store: ProvStore) -> None:
    """Write ADMIT's source stream, which it writes only when it admits the recording.

    Args:
        store: The store to write into.
    """
    activity = store.activity(node="ADMIT", step=None, parameters={})
    stream = store.entity(
        prov_type="stream", extent=(0.0, 1.0), attributes={"name": "recording", "sampling_rate": 16000}
    )
    store.was_generated_by(stream, activity)


def _replayed(tmp_path: Path, before: dict[str, Any], after: dict[str, Any], *, admitted: bool = True) -> ProvStore:
    """A store carrying two passes and the replay's edges between them.

    Args:
        tmp_path: A directory to round-trip the store through.
        before: Keyword arguments for the first pass's :func:`_write_pass`.
        after: Keyword arguments for the second's.
        admitted: Whether ADMIT admitted the recording and left its source stream behind.

    Returns:
        The replayed store.
    """
    first = ProvStore(run_id="run-a")
    if admitted:
        _admit(first)
    _write_pass(first, **before)
    path = tmp_path / "store.jsonl"
    first.write_jsonl(path)

    store = ProvStore.read_jsonl(path, run_id="run-a+replay-cafe")
    agent = software_agent(store)
    retired = retire_decisions(store, live_decisions(store), software=agent)
    _write_pass(store, **after)
    marker = store.activity(
        node=REPLAY_NODE,
        step=REPLAY_MARKER_STEP,
        parameters={"config_hash": "cafe", "commit": "a" * 40, "retired": len(retired)},
    )
    store.was_associated_with(marker, agent)
    return store


class TestSplitting:
    """The two passes come out of the edges, with no second tree to compare against."""

    def test_recovers_both_passes(self, tmp_path: Path) -> None:
        """Every entity the replay retired is the first pass; what a replayed node wrote is the second."""
        store = _replayed(tmp_path, {"fold": _fold()}, {"fold": _fold()})
        before, after = split_generations(store)
        assert [entity.prov_type for entity in before] == [entity.prov_type for entity in after]
        assert {entity.id for entity in before}.isdisjoint({entity.id for entity in after})
        assert all(store.is_invalidated(entity.id) for entity in before)
        assert not any(store.is_invalidated(entity.id) for entity in after)

    def test_preprocess_is_in_neither(self, tmp_path: Path) -> None:
        """The two nodes a replay reads off disk are not part of either decision."""
        store = _replayed(tmp_path, {"fold": _fold()}, {"fold": _fold()})
        before, after = split_generations(store)
        assert not [entity for entity in before + after if entity.prov_type == "word"]

    def test_both_generations_read_their_decision(self, tmp_path: Path) -> None:
        """Each pass's fold is recovered from its own verdict entity."""
        store = _replayed(tmp_path, {"fold": _fold(Triage.FLAG)}, {"fold": _fold(Triage.DISCARD)})
        before, after = split_generations(store)
        assert generation(store, before).value("triage") == "flag"
        assert generation(store, after).value("triage") == "discard"


class TestDecisionMovement:
    """What the file-level decision did, on both axes."""

    def test_unmoved_decision_reads_identical(self, tmp_path: Path) -> None:
        """The majority case says so plainly rather than being inferred from an empty diff."""
        row = diff_store(_replayed(tmp_path, {"fold": _fold()}, {"fold": _fold()}))
        assert row["status"] == OK
        assert row["identical"] is True
        assert row["transitions"]["triage"] == "pass->pass"

    def test_a_field_the_replay_added_is_not_a_move(self, tmp_path: Path) -> None:
        """A decision whose only difference is a field the first pass's commit did not have."""
        row = diff_store(
            _replayed(
                tmp_path,
                {"fold": _fold(), "drop": ("gates",)},
                {"fold": _fold(), "extra": {"gates": {"applied": []}}},
            )
        )
        assert row["identical"] is True
        assert row["new_keys"] == ["gates"]

    def test_triage_and_release_transitions(self, tmp_path: Path) -> None:
        """Both axes are reported, whichever one moved."""
        row = diff_store(
            _replayed(
                tmp_path,
                {"fold": _fold(Triage.FLAG)},
                {"fold": FileVerdict(triage=Triage.PASS, release=Release.RELEASABLE, declared_family="syllable")},
            )
        )
        assert row["transitions"]["triage"] == "flag->pass"
        assert row["transitions"]["release"] == "not_assessed->releasable"
        assert row["identical"] is False

    def test_grounds_gained_and_lost(self, tmp_path: Path) -> None:
        """A ground that appeared and one that went are each named, against their node."""
        gone = NodeVerdict(node="SPEECH", outcome=Outcome.FLAG, kind=None, why="the old ground on syllable")
        arrived = NodeVerdict(node="QUALITY", outcome=Outcome.FLAG, kind=None, why="the new ground on syllable")
        row = diff_store(
            _replayed(
                tmp_path,
                {"fold": _fold(Triage.FLAG, reasons=[gone])},
                {"fold": _fold(Triage.FLAG, reasons=[arrived])},
            )
        )
        assert row["grounds"] == {"gained": ["QUALITY|the new ground"], "lost": ["SPEECH|the old ground"]}

    def test_per_node_conformance_and_routes(self, tmp_path: Path) -> None:
        """A conformance or a route that moved is reported under the node or branch it belongs to."""
        row = diff_store(
            _replayed(
                tmp_path,
                {"fold": _fold(conformance={"SPEECH": True}, routes={"SPEECH": "routed", "VOICE": "declined"})},
                {"fold": _fold(conformance={"SPEECH": False}, routes={"SPEECH": "routed", "VOICE": "routed"})},
            )
        )
        assert row["moved"]["conformance"] == {"SPEECH": "True->False"}
        assert row["moved"]["routes"] == {"VOICE": "declined->routed"}


class TestTypedFindings:
    """The deviations a branch reported, in the fold and in the branch's own report."""

    def test_deviations_in_the_fold(self, tmp_path: Path) -> None:
        """A deviation type the replay's fold carries and the old one did not is a gain."""
        row = diff_store(
            _replayed(
                tmp_path,
                {"fold": _fold(deviations={"SPEECH": []})},
                {"fold": _fold(deviations={"SPEECH": ["off_task_extent"]})},
            )
        )
        assert row["moved"]["deviations"] == {"SPEECH": {"gained": ["off_task_extent"]}}

    def test_branch_report_deviations_are_read_separately(self, tmp_path: Path) -> None:
        """What the branch reported is compared apart from what the fold picked up."""
        row = diff_store(
            _replayed(
                tmp_path,
                {"fold": _fold(), "branch_deviations": ("off_task_extent",)},
                {"fold": _fold(), "branch_deviations": ()},
            )
        )
        assert row["report_deviations"] == {"SPEECH": {"lost": ["off_task_extent"]}}

    def test_assertions_are_counted_by_type_and_branch(self, tmp_path: Path) -> None:
        """The typed findings themselves are counted, not only the names the fold lists."""
        row = diff_store(
            _replayed(
                tmp_path,
                {"fold": _fold(), "deviation_assertions": ("off_task_extent",)},
                {"fold": _fold(), "deviation_assertions": ("off_task_extent", "off_task_extent")},
            )
        )
        assert row["deviation_assertions"] == {"SPEECH": {"off_task_extent": [1, 2]}}


class TestPii:
    """The change whose mistake leaks in one direction only."""

    def test_scanned_then_not_is_visible_on_the_row(self, tmp_path: Path) -> None:
        """A recording scanned before and not scanned now is readable off its own row."""
        row = diff_store(_replayed(tmp_path, {"fold": _fold(), "scanned": True}, {"fold": _fold(), "scanned": False}))
        assert row["pii"]["scanned"] == [True, False]
        assert row["identical"] is False

    def test_findings_and_categories_are_counted(self, tmp_path: Path) -> None:
        """The findings that went are counted by category and never by content."""
        row = diff_store(
            _replayed(
                tmp_path,
                {"fold": _fold(), "pii_categories": ("PERSON", "LOCATION")},
                {"fold": _fold(), "pii_categories": ("PERSON",)},
            )
        )
        assert row["pii"]["findings_n"] == [2, 1]
        assert row["pii"]["categories"] == {"LOCATION": [1, 0]}

    def test_redact_run_state_is_paired(self, tmp_path: Path) -> None:
        """REDACT's run state is carried on the PII axis, since the scan is what gates it."""
        ran_before = {"SPEECH": RunState.COMPLETED, "REDACT": RunState.COMPLETED}
        ran_after = {"SPEECH": RunState.COMPLETED, "REDACT": RunState.SKIPPED}
        row = diff_store(_replayed(tmp_path, {"fold": _fold(ran=ran_before)}, {"fold": _fold(ran=ran_after)}))
        assert row["pii"]["redact_ran"] == ["completed", "skipped"]


class TestRedaction:
    """The report will be read to judge a PII change, so it is the one most at risk of quoting."""

    def test_no_stored_text_reaches_a_row(self, tmp_path: Path) -> None:
        """A word's text and a finding's surface are in the store and in neither pass's row."""
        store = _replayed(
            tmp_path,
            {"fold": _fold(), "pii_categories": ("PERSON",), "deviation_assertions": ("off_task_extent",)},
            {"fold": _fold(), "pii_categories": (), "deviation_assertions": ()},
        )
        assert SECRET in (tmp_path / "store.jsonl").read_text()
        row = diff_store(store)
        assert SECRET not in json.dumps(row)

    def test_no_stored_text_reaches_the_report(self, tmp_path: Path) -> None:
        """Nor does it survive the fold and the rendering."""
        store = _replayed(tmp_path, {"fold": _fold(), "pii_categories": ("PERSON",)}, {"fold": _fold()})
        report = aggregate([{**diff_store(store), "stem": "sub-a_task-vowel"}])
        assert SECRET not in render_markdown(report, tmp_path)


class TestUnreplayed:
    """A store the replay has not reached is a status, not a failure."""

    def test_a_store_with_no_marker_is_not_replayed(self, tmp_path: Path) -> None:
        """Reading one while the array is still running says so rather than inventing a diff."""
        store = ProvStore(run_id="run-a")
        _write_pass(store, _fold())
        assert diff_store(store) == {"status": NOT_REPLAYED}

    def test_a_missing_store_is_a_status(self, tmp_path: Path) -> None:
        """A run root the replay has not written yet reads as ``no_store``."""
        assert diff_run(tmp_path, stem="sub-a")["status"] == NO_STORE

    def test_a_run_that_decided_nothing_before_is_not_identical(self, tmp_path: Path) -> None:
        """A corpus run that left no decision for the replay to retire reads against ``UNREAD``."""
        first = ProvStore(run_id="run-a")
        _admit(first)
        path = tmp_path / "store.jsonl"
        first.write_jsonl(path)
        store = ProvStore.read_jsonl(path, run_id="run-a+replay-cafe")
        agent = software_agent(store)
        _write_pass(store, _fold())
        marker = store.activity(
            node=REPLAY_NODE, step=REPLAY_MARKER_STEP, parameters={"config_hash": "cafe", "commit": None}
        )
        store.was_associated_with(marker, agent)
        row = diff_store(store)
        assert row["status"] == NOTHING_RETIRED
        assert row["transitions"]["triage"] == "UNREAD->pass"
        assert row["identical"] is False

    def test_two_replays_are_ambiguous(self, tmp_path: Path) -> None:
        """Retirements carry no pass of their own, so a twice-replayed store says so."""
        store = _replayed(tmp_path, {"fold": _fold()}, {"fold": _fold()})
        second = store.activity(
            node=REPLAY_NODE, step=REPLAY_MARKER_STEP, parameters={"config_hash": "f00d", "commit": None}
        )
        store.was_associated_with(second, software_agent(store))
        row = diff_store(store)
        assert row["status"] == AMBIGUOUS
        assert row["config_hash"] == ["cafe", "f00d"]


class TestNotReplayable:
    """A run whose replayed nodes had nothing to read moved nothing, whatever its store says."""

    def test_a_run_admit_rejected_is_excluded(self, tmp_path: Path) -> None:
        """Without ADMIT's source stream the replay calls what the original run skipped."""
        store = _replayed(
            tmp_path,
            {"fold": _fold(ran={"PREPROCESS": RunState.SKIPPED, "QUALITY": RunState.SKIPPED})},
            {"fold": _fold(ran={"PREPROCESS": RunState.SKIPPED, "QUALITY": RunState.ERRORED})},
            admitted=False,
        )
        row = diff_store(store)
        assert row["status"] == NOT_REPLAYABLE
        assert row["blocker"] == ADMIT_DID_NOT_ADMIT

    def test_a_run_preprocess_did_not_finish_is_excluded(self, tmp_path: Path) -> None:
        """ADMIT admitted it and PREPROCESS left no conditioned output, which is the same artefact."""
        store = _replayed(
            tmp_path,
            {"fold": _fold(ran={"PREPROCESS": RunState.ERRORED})},
            {"fold": _fold(ran={"PREPROCESS": RunState.ERRORED})},
        )
        row = diff_store(store)
        assert row["status"] == NOT_REPLAYABLE
        assert row["blocker"] == PREPROCESS_DID_NOT_COMPLETE

    def test_an_admitted_and_preprocessed_run_is_compared(self, tmp_path: Path) -> None:
        """The gate only excludes; a run that carries both is compared as before."""
        store = _replayed(
            tmp_path,
            {"fold": _fold(ran={"PREPROCESS": RunState.COMPLETED})},
            {"fold": _fold(ran={"PREPROCESS": RunState.COMPLETED})},
        )
        assert diff_store(store)["status"] == OK

    def test_they_are_counted_apart_and_named(self, tmp_path: Path) -> None:
        """The excluded runs reach neither the transition matrix nor the identical count."""
        for name in "ab":
            (tmp_path / name).mkdir()
        blocked = _replayed(
            tmp_path / "a",
            {"fold": _fold(Triage.DISCARD, ran={"PREPROCESS": RunState.SKIPPED})},
            {"fold": _fold(Triage.FLAG, ran={"PREPROCESS": RunState.SKIPPED})},
            admitted=False,
        )
        fine = _replayed(
            tmp_path / "b",
            {"fold": _fold(ran={"PREPROCESS": RunState.COMPLETED})},
            {"fold": _fold(ran={"PREPROCESS": RunState.COMPLETED})},
        )
        report = aggregate([{**diff_store(blocked), "stem": "sub-blocked"}, {**diff_store(fine), "stem": "sub-fine"}])
        assert report.compared == 1
        assert report.triage == {"pass->pass": 1}
        assert report.not_replayable["count"] == 1
        assert report.not_replayable["stems"] == ["sub-blocked"]
        rendered = render_markdown(report, tmp_path)
        assert "1 not replayable and excluded" in rendered
        assert "`sub-blocked`" in rendered
        assert "discard" not in rendered


class TestAggregate:
    """The corpus fold over the rows, and what the report leads with."""

    def _rows(self, tmp_path: Path) -> list[dict[str, Any]]:
        """Three recordings: two unmoved, one whose scan and triage both moved."""
        unmoved = _replayed(tmp_path / "a", {"fold": _fold()}, {"fold": _fold()})
        same = _replayed(tmp_path / "b", {"fold": _fold()}, {"fold": _fold()})
        moved = _replayed(
            tmp_path / "c",
            {"fold": _fold(Triage.FLAG), "scanned": True, "pii_categories": ("PERSON",)},
            {"fold": _fold(Triage.PASS), "scanned": False},
        )
        return [
            {**diff_store(store), "stem": stem}
            for store, stem in ((unmoved, "sub-a"), (same, "sub-b"), (moved, "sub-c"))
        ]

    def test_identical_is_the_headline(self, tmp_path: Path) -> None:
        """The majority case is counted and named, not left to be inferred."""
        for name in "abc":
            (tmp_path / name).mkdir()
        report = aggregate(self._rows(tmp_path))
        assert (report.compared, report.identical) == (3, 2)
        assert "2 decisions did not move at all" in render_markdown(report, tmp_path)

    def test_the_moved_recordings_are_named(self, tmp_path: Path) -> None:
        """A transition that moved carries the stems that took it."""
        for name in "abc":
            (tmp_path / name).mkdir()
        report = aggregate(self._rows(tmp_path))
        assert report.triage == {"pass->pass": 2, "flag->pass": 1}
        assert report.moved_stems["triage"] == {"flag->pass": ["sub-c"]}

    def test_the_leaking_direction_has_its_own_count(self, tmp_path: Path) -> None:
        """Scanned before and not now is counted apart and named in the report."""
        for name in "abc":
            (tmp_path / name).mkdir()
        report = aggregate(self._rows(tmp_path))
        assert report.pii_scanned_then_not["count"] == 1
        assert report.pii_scanned_then_not["stems"] == ["sub-c"]
        assert report.pii_not_scanned_then_now["count"] == 0
        rendered = render_markdown(report, tmp_path)
        assert "scanned before, not scanned now: 1" in rendered
        assert "`sub-c`" in rendered

    def test_typed_findings_report_their_totals(self, tmp_path: Path) -> None:
        """The assertions table names what each pass wrote, not only how many recordings moved."""
        store = _replayed(
            tmp_path,
            {"fold": _fold(), "deviation_assertions": ("truncation",)},
            {"fold": _fold(), "deviation_assertions": ("truncation", "truncation")},
        )
        report = aggregate([{**diff_store(store), "stem": "sub-a"}])
        assert report.deviation_assertions["SPEECH"]["truncation"] == {"before": 1, "after": 2, "gained": 1}
        assert "| `SPEECH` | `truncation` | 1 | 2 | 1 | 0 |" in render_markdown(report, tmp_path)

    def test_products_round_trip(self, tmp_path: Path) -> None:
        """Both products are written, and the JSON reads back as what was counted."""
        for name in "abc":
            (tmp_path / name).mkdir()
        rows_dir = tmp_path / "rows"
        rows_dir.mkdir()
        (rows_dir / "slice.jsonl").write_text(
            "".join(json.dumps(row, sort_keys=True) + "\n" for row in self._rows(tmp_path)), encoding="utf-8"
        )
        report = aggregate(read_rows(rows_dir))
        json_path, markdown_path = write_report(report, tmp_path / "out", rows_dir)
        assert json.loads(json_path.read_text())["identical"] == 2
        assert markdown_path.read_text().startswith("# What the replay changed")
