"""Measuring what TAXONOMY would have to read to route a recording to a branch.

Reads a completed triage run's provenance stores, extracts the evidence each candidate routing
detector would use, and scores every detector over a threshold sweep against a stated reference
standard. Runs no model and writes nothing into a run directory.

The reference standards, their weakness and the measurements taken with this module live in
``specs/20260910-taxonomy-routing-evidence/``.
"""

from senselab.audio.workflows.triage.routing_analysis.detectors import (
    BRANCH_DETECTORS,
    DETECTORS,
    STAGED_DETECTORS,
    Detector,
    detector_value,
    sweep_points,
)
from senselab.audio.workflows.triage.routing_analysis.families import declared_kinds, task_family, task_id_of
from senselab.audio.workflows.triage.routing_analysis.features import (
    RecordingFeatures,
    bracket_type,
    extract_features,
    invalidated_ids,
    onomatopoeic_vocabulary,
    read_store,
    span_label_memberships,
    value_stats,
)
from senselab.audio.workflows.triage.routing_analysis.gate_matrix import (
    DECIDING_CLASSES,
    DISAGREEMENT_KINDS,
    EXTRA,
    MISSED,
    Deciding,
    Disagreement,
    DisagreementGroup,
    GateCell,
    GateMatrix,
    gate_matrix,
    gate_order,
    group_disagreements,
    load_disagreement_profile,
    qualify_disagreements,
    relative_margin,
    routing_branch_of,
    unassigned_families,
)
from senselab.audio.workflows.triage.routing_analysis.gate_plot import (
    FIRED_PANEL,
    PANELS,
    UNAVAILABLE_PANEL,
    HeatmapStyle,
    draw_gate_matrix,
    write_gate_matrix,
)
from senselab.audio.workflows.triage.routing_analysis.report import (
    BASELINE_RULES,
    REFERENCE_STANDARDS,
    Confusion,
    ReferenceStandard,
    RoutingRule,
    bucket_augmentation,
    bucket_coverage,
    disagreements,
    dump_features,
    load_feature_column,
    load_features,
    prevalence,
    score_detector,
    shard_files,
    taxonomy_as_run,
    write_report,
)
from senselab.audio.workflows.triage.routing_analysis.ruleset import (
    FAMILY_SETS,
    ROUTE_STATES,
    Emptiness,
    FamilyTally,
    Gate,
    GateOutcome,
    RouteEvaluation,
    RouteState,
    Ruleset,
    evaluate_emptiness,
    evaluate_gate,
    evaluate_routes,
    gate_outcome_of,
    gate_value,
    load_ruleset,
    max_token_repeat,
    score_branches,
    tally_families,
)

__all__ = [
    "BASELINE_RULES",
    "BRANCH_DETECTORS",
    "Confusion",
    "DECIDING_CLASSES",
    "DETECTORS",
    "DISAGREEMENT_KINDS",
    "Deciding",
    "Detector",
    "Disagreement",
    "DisagreementGroup",
    "EXTRA",
    "Emptiness",
    "FAMILY_SETS",
    "FIRED_PANEL",
    "FamilyTally",
    "Gate",
    "GateCell",
    "GateMatrix",
    "GateOutcome",
    "HeatmapStyle",
    "MISSED",
    "PANELS",
    "REFERENCE_STANDARDS",
    "ROUTE_STATES",
    "RecordingFeatures",
    "ReferenceStandard",
    "RouteEvaluation",
    "RouteState",
    "RoutingRule",
    "Ruleset",
    "STAGED_DETECTORS",
    "UNAVAILABLE_PANEL",
    "bracket_type",
    "bucket_augmentation",
    "bucket_coverage",
    "declared_kinds",
    "detector_value",
    "disagreements",
    "draw_gate_matrix",
    "dump_features",
    "evaluate_emptiness",
    "evaluate_gate",
    "evaluate_routes",
    "extract_features",
    "gate_matrix",
    "gate_order",
    "gate_outcome_of",
    "gate_value",
    "group_disagreements",
    "invalidated_ids",
    "load_disagreement_profile",
    "load_feature_column",
    "load_features",
    "load_ruleset",
    "max_token_repeat",
    "onomatopoeic_vocabulary",
    "prevalence",
    "qualify_disagreements",
    "read_store",
    "relative_margin",
    "routing_branch_of",
    "score_branches",
    "score_detector",
    "shard_files",
    "span_label_memberships",
    "sweep_points",
    "tally_families",
    "task_family",
    "task_id_of",
    "taxonomy_as_run",
    "unassigned_families",
    "value_stats",
    "write_gate_matrix",
    "write_report",
]
