name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Includes getting tags
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        which python
        python --version
        pip install poetry==2.1.3
        which poetry
        poetry --version
      shell: bash
    - name: Install dependencies with Poetry
      run: |
        poetry install
      shell: bash
    - name: Build package
      run: poetry build
      shell: bash
    - name: Configure Poetry PyPI token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      shell: bash
    - name: Publish to PyPI
      env:
        POETRY_REQUESTS_TIMEOUT: 120
      run: poetry publish
      shell: bash
